import { ConnectButton } from "@rainbow-me/rainbowkit";
import type { NextPage } from "next";
import Head from "next/head";

import { TodoList } from "contracts";
import { Text } from "ui-kit";

import { ContractGUI } from "../components/ContractGUI/ContractGUI";

const contracts = {
  TodoList: {
    abi: TodoList,
    address: "0x5fbdb2315678afecb367f032d93f642f64180aa3",
  },
};

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Contracts GUI</title>
        <meta
          content="Generated by @rainbow-me/create-rainbowkit"
          name="description"
        />
        <link href="/favicon.ico" rel="icon" />
      </Head>

      <nav className="flex justify-between items-center border-b py-2 px-4 mb-8">
        <Text.H4 as="div">Contract GUI</Text.H4>
        <ConnectButton />
      </nav>

      <main className="px-4">
        <ContractGUI contracts={contracts} />
      </main>
    </div>
  );
};

export default Home;
