import { ConnectButton } from "@rainbow-me/rainbowkit";
import type { NextPage } from "next";
import Head from "next/head";
import { usePublicClient } from "wagmi";

import { TodoList, TestSolidityTypes } from "contracts";
import { Text } from "ui-kit";

import { ContractGUI } from "../components/ContractGUI/ContractGUI";
import { ThemeToggle } from "../components/ThemeProvider/ThemeProvider";

const contracts = {
  TodoList: {
    abi: TodoList,
    address: "0xc6e7df5e7b4f2a278906862b61205850344d4e7d",
  },
  TestSolidityTypes: {
    abi: TestSolidityTypes,
    address: "0x59b670e9fa9d0a427751af201d676719a970857b",
  },
};

function useTestingTypes() {
  const publicClient = usePublicClient();
  publicClient.readContract({
    address: "0x59b670e9fa9d0a427751af201d676719a970857b",
    abi: TestSolidityTypes,
    functionName: "echoArray",
    args: [],
  });
}

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Contracts GUI</title>
        <meta
          content="Generated by @rainbow-me/create-rainbowkit"
          name="description"
        />
        <link href="/favicon.ico" rel="icon" />
      </Head>

      <nav className="flex justify-between items-center border-b py-2 px-4 sticky top-0 bg-card">
        <Text.H3 as="div">Contract GUI</Text.H3>
        <div className="flex items-center gap-3">
          <ThemeToggle />
          <ConnectButton />
        </div>
      </nav>

      <main className="px-4">
        <ContractGUI contracts={contracts} />
      </main>
    </div>
  );
};

export default Home;
