import { ConnectButton } from "@rainbow-me/rainbowkit";
import type { NextPage } from "next";
import Head from "next/head";

import { TodoList, TestSolidityTypes } from "contracts";
import { Text } from "ui-kit";

import { ContractGUI } from "../components/ContractGUI/ContractGUI";
import { ThemeToggle } from "../components/ThemeProvider/ThemeProvider";

const contracts = {
  TodoList: {
    abi: TodoList,
    address: "0x0165878a594ca255338adfa4d48449f69242eb8f",
  },
  TestSolidityTypes: {
    abi: TestSolidityTypes,
    address: "0xa513e6e4b8f2a923d98304ec87f64353c4d5c853",
  },
};

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Contracts GUI</title>
        <meta
          content="Generated by @rainbow-me/create-rainbowkit"
          name="description"
        />
        <link href="/favicon.ico" rel="icon" />
      </Head>

      <nav className="flex justify-between items-center border-b py-2 px-4 sticky top-0 bg-card">
        <Text.H3 as="div">Contract GUI</Text.H3>
        <div className="flex items-center gap-3">
          <ThemeToggle />
          <ConnectButton />
        </div>
      </nav>

      <main className="px-4">
        <ContractGUI contracts={contracts} />
      </main>
    </div>
  );
};

export default Home;
