import { ConnectButton } from "@rainbow-me/rainbowkit";
import { GetServerSideProps } from "next";
import { Creepster } from "next/font/google";
import Head from "next/head";
import { ComponentProps } from "react";

import { cn } from "ui-utils";

import { ContractGUI } from "../components/ContractGUI/ContractGUI";
import { ThemeToggle } from "../components/ThemeProvider/ThemeProvider";
import { getContractsMap } from "../lib/getContractsMap";

const creepster = Creepster({
  subsets: ["latin"],
  weight: "400",
});

type Props = ComponentProps<typeof ContractGUI>;

export default function Home({ contracts }: Props) {
  return (
    <div>
      <Head>
        <title>Contract GUI</title>
        <meta
          content="Generated by @rainbow-me/create-rainbowkit"
          name="description"
        />
        <link href="/favicon.ico" rel="icon" />
      </Head>

      <nav className="flex justify-between items-center border-b py-2 px-4 sticky top-0 bg-card">
        <span className={cn(creepster.className, "text-4xl")}>
          Contract GUI
        </span>
        <div className="flex items-center gap-3">
          <ThemeToggle />
          <ConnectButton />
        </div>
      </nav>

      <main className="px-4">
        <ContractGUI contracts={contracts} />
      </main>
    </div>
  );
}

export const getServerSideProps = (async () => {
  const contractsMap = await getContractsMap();
  return {
    props: {
      contracts: contractsMap,
    },
  };
}) satisfies GetServerSideProps<Props>;
