import { ConnectButton } from "@rainbow-me/rainbowkit";
import type { NextPage } from "next";
import Head from "next/head";
import * as contracts from "contracts";
import { Dropdown } from "../components/Dropdown/Dropdown";
import { DropdownMenuDemo } from "../components/DropdownMenuDemo";

console.log(contracts);

const contractNames = Object.keys(contracts) as Array<keyof typeof contracts>;

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Gooey ABI | Solidity Contract UI</title>
        <meta
          content="Generated by @rainbow-me/create-rainbowkit"
          name="description"
        />
        <link href="/favicon.ico" rel="icon" />
      </Head>

      <div className="container mx-auto p-4">
        <main>
          <div className="flex items-center justify-between mb-4">
            <h1 className="font-bold text-xl">Gooey ABI</h1>
            <ConnectButton />
          </div>

          <div className="flex items-center">
            <h2 className="font-bold mr-2">Contract:</h2>
            {/* <Dropdown options={contractNames} /> */}
            <DropdownMenuDemo />
          </div>
        </main>

        <footer>
          <a href="#" rel="noopener noreferrer" target="_blank">
            Made by dan
          </a>
        </footer>
      </div>
    </>
  );
};

export default Home;
