import { ConnectButton } from "@rainbow-me/rainbowkit";
import type { NextPage } from "next";
import { Creepster } from "next/font/google";
import Head from "next/head";

import { TodoList, TestSolidityTypes, contractAddresses } from "contracts";
import { cn } from "ui-utils";

import { ContractGUI } from "../components/ContractGUI/ContractGUI";
import { ThemeToggle } from "../components/ThemeProvider/ThemeProvider";

const contracts = {
  TodoList: {
    abi: TodoList,
    address: contractAddresses.localhost.TodoList,
  },
  TestSolidityTypes: {
    abi: TestSolidityTypes,
    address: contractAddresses.localhost.TestSolidityTypes,
  },
};

const creepster = Creepster({
  subsets: ["latin"],
  weight: "400",
});

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Gooey ABI</title>
        <meta
          content="Generated by @rainbow-me/create-rainbowkit"
          name="description"
        />
        <link href="/favicon.ico" rel="icon" />
      </Head>

      <nav className="flex justify-between items-center border-b py-2 px-4 sticky top-0 bg-card">
        <span className={cn(creepster.className, "text-4xl")}>Gooey ABI</span>
        <div className="flex items-center gap-3">
          <ThemeToggle />
          <ConnectButton />
        </div>
      </nav>

      <main className="px-4">
        <ContractGUI contracts={contracts} />
      </main>
    </div>
  );
};

export default Home;
